// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleMaintenance.Data;

#nullable disable

namespace VehicleMaintenance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407165757_maintenancerecordcomponent")]
    partial class maintenancerecordcomponent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.LiquidEntry", b =>
                {
                    b.Property<int>("LiquidEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LiquidEntryId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LiquidType")
                        .HasColumnType("int");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefillDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("LiquidEntryId");

                    b.HasIndex("VehicleId");

                    b.ToTable("LiquidEntries");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.MaintenanceRecord", b =>
                {
                    b.Property<int>("MaintenanceRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceRecordId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PredictionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("MaintenanceRecordId");

                    b.HasIndex("PredictionId");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.MaintenanceRecordComponent", b =>
                {
                    b.Property<int>("MaintenanceRecordComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceRecordComponentId"));

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<string>("ChangedParts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LaborCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LaborMinutes")
                        .HasColumnType("int");

                    b.Property<int>("MaintenanceRecordId")
                        .HasColumnType("int");

                    b.Property<int?>("NewState")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OldState")
                        .HasColumnType("int");

                    b.Property<decimal?>("OtherCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PartsCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TechnicianName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorOrShop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaintenanceRecordComponentId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("MaintenanceRecordId");

                    b.ToTable("MaintenanceRecordComponents");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.Prediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredictionId"));

                    b.Property<int>("ComponentType")
                        .HasColumnType("int");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PredictedServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VehicleComponentComponentId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("PredictionId");

                    b.HasIndex("VehicleComponentComponentId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DrivingExperience")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EngineType")
                        .HasColumnType("int");

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransmissionType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.Property<int>("YearOfProduction")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.VehicleComponent", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComponentId"));

                    b.Property<int>("ComponentType")
                        .HasColumnType("int");

                    b.Property<int>("CurrentMileage")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedLifetimeKm")
                        .HasColumnType("int");

                    b.Property<int>("ExpectedLifetimeYears")
                        .HasColumnType("int");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("ComponentId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleComponents");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.LiquidEntry", b =>
                {
                    b.HasOne("VehicleMaintenance.Models.Entities.Vehicle", "Vehicle")
                        .WithMany("LiquidEntries")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("VehicleMaintenance.Models.Entities.Prediction", null)
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("PredictionId");

                    b.HasOne("VehicleMaintenance.Models.Entities.Vehicle", "Vehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.MaintenanceRecordComponent", b =>
                {
                    b.HasOne("VehicleMaintenance.Models.Entities.VehicleComponent", "Component")
                        .WithMany("MaintenanceRecordComponents")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleMaintenance.Models.Entities.MaintenanceRecord", "MaintenanceRecord")
                        .WithMany("MaintenanceRecordComponents")
                        .HasForeignKey("MaintenanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("MaintenanceRecord");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.Prediction", b =>
                {
                    b.HasOne("VehicleMaintenance.Models.Entities.VehicleComponent", null)
                        .WithMany("Predictions")
                        .HasForeignKey("VehicleComponentComponentId");

                    b.HasOne("VehicleMaintenance.Models.Entities.Vehicle", "Vehicle")
                        .WithMany("Predictions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.Vehicle", b =>
                {
                    b.HasOne("VehicleMaintenance.Models.Entities.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.VehicleComponent", b =>
                {
                    b.HasOne("VehicleMaintenance.Models.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleComponents")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.MaintenanceRecord", b =>
                {
                    b.Navigation("MaintenanceRecordComponents");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.Prediction", b =>
                {
                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.User", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.Vehicle", b =>
                {
                    b.Navigation("LiquidEntries");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("Predictions");

                    b.Navigation("VehicleComponents");
                });

            modelBuilder.Entity("VehicleMaintenance.Models.Entities.VehicleComponent", b =>
                {
                    b.Navigation("MaintenanceRecordComponents");

                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
